apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-on-aws-app
  labels:
    app: kubernetes-on-aws-app
spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: kubernetes-on-aws
  template:
    metadata:
      labels:
        app: kubernetes-on-aws
    spec: 
      containers:
        -name: kubernetes-on-aws
        images: iniakpothompson/slow-node-base
        ports:
          -containerPort: 80
"deployment.yaml" 22L, 353C
